version: '3'
services:
  mongo:
    image: mongo:3
    ports:
      - "27017:27017"
    networks:
      - thisnet
    volumes:
      - mongodata:/data/db
  gateway:
    image: codate/gateway:latest
    ports:
      - "80:80"
    links:
      - auth:authserver
      - file:fileserver
      - exam:examserver
    extra_hosts:
      - "staticserver:172.50.4.148"
    networks:
      - thisnet
    depends_on:
      - file
      - auth
      - exam
  file:
    image: codate/file:latest
    ports:
      - "8081:8081"
    networks:
      - thisnet
    environment:
      - PORT=8081
      - URL=mongodb://mongo:27017/file
    depends_on:
      - mongo
  auth:
    image: codate/auth:latest
    ports:
      - "8082:8082"
    networks:
      - thisnet
    environment:
      - PORT=8082
      - DB_URL=mongodb://mongo:27017/auth
      - DOMAIN=localhost
    depends_on:
      - mongo
  exam:
    image: codate/exam:latest
    ports:
      - "8083:8083"
    networks:
      - thisnet
    environment:
      - PORT=8083
      - DB_URL=mongodb://mongo:27017/exam
      - URL_FILE_SERVICE=http://localhost/api/files
    depends_on:
      - mongo
volumes:
  mongodata:
networks:
  thisnet:
