export default {
    actions: {
        UPLOAD_FILE: 'UPLOAD_FILE',
        REGISTER: 'REGISTER',
        LOGIN: 'LOGIN',
        CHECK_EMAIL: 'CHECK_EMAIL',
        CREATE_EXAM: 'CREATE_EXAM',
        GET_MY_EXAMS: 'GET_MY_EXAMS'
    },
    mutations: {
        SET_TOKEN: 'SET_TOKEN',
        SET_FILE_UPLOAD_PROGRESS: 'SET_FILE_UPLOAD_PROGRESS',
        SET_LOADING: 'SET_LOADING',
        SET_UNLOADING: 'SET_UNLOADING',
        SET_FILE_UPLOAD_NAME: 'SET_FILE_UPLOAD_NAME',
        SET_LOGGED_USER: 'SET_LOGGED_USER',
        SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
        SET_INFO_MESSAGE: 'SET_INFO_MESSAGE',
        RESET_FILE_UPLOAD: 'RESET_FILE_UPLOAD'
    }
}
